module.exports={
    TUTOR_COLLECTION:'tutor',
    STUDENT_COLLECTION:'student',
    ASSIGNMENT_COLLECTION:'assignment',
    STUDENT_ASSIGNMENTS_COLLECTION:'studentAssignments',
    NOTES_COLLECTION:'notes',
    ANNOUNCEMENT_COLLECTION:'announcement',
    PHOTO_COLLECTION:'photo',
    EVENT_COLLECTION:'event'
}